### ISSUE TITLE
Locale issues

### ISSUE THREAD

**Issue by EgorBlagov** [ForsakenNGS/DruidMacroHelper#4]
Hi, thanks a lot for this addon, it's extremely useful. Unfortunately my friend faced an issue on Russian server.

We use some regular macro:

```
#showtooltip
/stopattack
/click dmhStart
/dmh cd pot
/use Слабое зелье маны
/click dmhEnd
/startattack
```
The macro checks GCD, character leaves bear form, drinks potion but doesn't enter the form again.
I've checked locally by replacing EN Spell names (e.g. **Dire Bear Form**) with RU spell names (e.g. [**Облик лютого медведя** ](https://ru.tbc.wowhead.com/spell=9634)) and the macro started to work fine.

I'm not aware on API and how to debug the stuff, but I've checked the guess on localizing spell names using [GetText](https://wowwiki-archive.fandom.com/wiki/API_GetText)

```lua
self:CreateButton('dmhEnd', string.format('/use [bar:2]!%s;[bar:3]!%s;[bar:4]!%s\n/click dmhReset\n/dmh end', GetText('Dire Bear Form'), GetText('Cat Form'), GetText('Travel Form')), 'Change back to form based on the current bar. (includes /dmh end)');
```

But that didn't work. You are more experienced in that, could you let us know if it's possible to fix, and fix it in the repo, so in each update we won't need to adjust the script.

Thanks & Regards,
Egor

**Comment by ForsakenNGS** [comment]
I added translation files and the (hopefully accurate) translations from wowhead.

**Comment by kiboys** [comment]
The issue still exist on zhTW (traditional Chinese version) of the game. I tried to mimic the local zhTW.lua in the folder:
--localization file for Taiwan
local _, L = ...;
if GetLocale() ~= "zhTW" then return end

L["FORM_DIRE_BEAR"] = "巨熊形態"
L["FORM_CAT"] = "獵豹形態"
L["FORM_TRAVEL"] = "旅行形態"

**Comment by kiboys** [comment]
Confirmed working now!
